// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineSurveyAPI.DBContexts;

namespace OnlineSurveyAPI.Migrations
{
    [DbContext(typeof(SurveyDBContext))]
    [Migration("20190729032254_20190727_Initial")]
    partial class _20190727_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineSurveyAPI.Model.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId");

                    b.Property<string>("CustomerName");

                    b.Property<string>("Email");

                    b.Property<int>("SurveyId");

                    b.Property<string>("SurveyName");

                    b.HasKey("Id");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("OnlineSurveyAPI.Model.SurveyList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SurveyKey");

                    b.Property<string>("SurveyQuestion");

                    b.HasKey("Id");

                    b.ToTable("SurveyList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SurveyKey = "Answer 001",
                            SurveyQuestion = "Question 001"
                        },
                        new
                        {
                            Id = 2,
                            SurveyKey = "Answer 002",
                            SurveyQuestion = "Question 002"
                        },
                        new
                        {
                            Id = 3,
                            SurveyKey = "Answer 003",
                            SurveyQuestion = "Question 003"
                        },
                        new
                        {
                            Id = 4,
                            SurveyKey = "Answer 004",
                            SurveyQuestion = "Question 004"
                        },
                        new
                        {
                            Id = 5,
                            SurveyKey = "Answer 005",
                            SurveyQuestion = "Question 005"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
